<a href="https://colab.research.google.com/github/hussainbabar/pytorch_Practice/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Lists

In [2]:
my_List = [1,2,3,4]
my_List


[1, 2, 3, 4]

In [4]:
# Numpys
import numpy as np


In [5]:
np1 = np.random.rand(3,4)
np1

array([[0.01328996, 0.36919728, 0.47056201, 0.99907464],
       [0.44143624, 0.34496719, 0.00696523, 0.36057222],
       [0.72723863, 0.16287153, 0.91702746, 0.59293709]])

## Tensors

In [6]:
np2 = np.random.rand(3,4,2)
np2

array([[[0.33968477, 0.48429836],
        [0.3636794 , 0.61836678],
        [0.98525464, 0.64891746],
        [0.5482148 , 0.97126664]],

       [[0.02449753, 0.5335496 ],
        [0.15475708, 0.88057143],
        [0.56903534, 0.22381787],
        [0.76464181, 0.54064256]],

       [[0.82793346, 0.67386805],
        [0.19175725, 0.43702244],
        [0.04659405, 0.93246615],
        [0.94976527, 0.67197545]]])

# Tesnors

In [4]:
import torch

x = torch.empty(1)
x

tensor([2.7203e+22])

In [8]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.3846, -0.3433,  1.3831,  0.3911],
        [ 0.2100, -0.1589, -0.1930, -0.8851],
        [ 1.5725,  0.5584, -0.4734,  1.0672]])

In [5]:
tensor_3d = torch.randn(3,4,5)
tensor_3d

tensor([[[ 0.1469, -0.1761,  0.1027,  0.6834, -0.9156],
         [-0.4371, -0.3154,  2.1673,  0.0522,  0.3923],
         [ 1.1178, -0.6853,  0.2983,  0.1486, -0.2296],
         [ 0.2246, -0.0181, -1.2331,  1.0245,  0.1015]],

        [[ 1.2531,  0.1873, -1.2714,  0.3958, -1.5595],
         [ 0.1168, -0.5732,  1.1179,  1.8340, -1.1022],
         [-0.0538, -1.6342, -1.4121,  0.9942,  0.1998],
         [-0.3411,  1.0318, -1.0848,  1.9026, -0.4057]],

        [[ 1.0149,  0.6012,  0.4595, -1.5522,  1.9888],
         [ 0.7238,  0.1775,  0.0416, -0.4008,  0.3972],
         [-0.9326, -1.2744, -1.5580, -0.9725, -1.2171],
         [-1.0379, -0.1053,  0.0640, -1.0808, -0.3307]]])



1.   Tesnors is a multi dimnesional matrix containing elements of a single data type
2.   Similar to numpys arrays, full of fun that make them work better on GPU

3. Default datatype is flot32
4. More suitable for deep learning than a numpy




